import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-beverage-depletion-allowance-reconciliation",
  "engine": "recovery",
  "title": "Beverage Depletion Allowance Reconciliation",
  "shortTitle": "Beverage Depletion Allowance Reconciliation",
  "tagline": "Reconcile distributor depletion, billback, and promotional allowances to verified account-level sales.",
  "industry": "Beverage Revenue Operations",
  "buyer": "Beverage producers and distributors",
  "uiPort": 4708,
  "apiPort": 5708,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Beverage Depletion Allowance Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits in one accountable workflow. Reconcile distributor depletion, billback, and promotional allowances to verified account-level sales.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Beverage Depletion Allowance Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("distributor-agreement-library","BDA01","Distributor agreement library","Execute distributor agreement library using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed distributor agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Distributor agreement library Reference","text","BDA01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("brand-sku-registry","BDA02","Brand SKU registry","Execute brand sku registry using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed brand sku registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Brand SKU registry Reference","text","BDA02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("territory-account-mapping","BDA03","Territory account mapping","Execute territory account mapping using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed territory account mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Territory account mapping Reference","text","BDA03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("depletion-report-ingestion","BDA04","Depletion report ingestion","Execute depletion report ingestion using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed depletion report ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Depletion report ingestion Reference","text","BDA04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("account-eligibility-validation","BDA05","Account eligibility validation","Execute account eligibility validation using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed account eligibility validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Account eligibility validation Reference","text","BDA05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("volume-tier-calculation","BDA06","Volume tier calculation","Execute volume tier calculation using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed volume tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Volume tier calculation Reference","text","BDA06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("promotional-period-control","BDA07","Promotional period control","Execute promotional period control using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed promotional period control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Promotional period control Reference","text","BDA07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("billback-calculation","BDA08","Billback calculation","Execute billback calculation using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed billback calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Billback calculation Reference","text","BDA08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("display-allowance-evidence","BDA09","Display allowance evidence","Execute display allowance evidence using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed display allowance evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Display allowance evidence Reference","text","BDA09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("duplicate-claim-detection","BDA10","Duplicate claim detection","Execute duplicate claim detection using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed duplicate claim detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Duplicate claim detection Reference","text","BDA10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("distributor-deduction-matching","BDA11","Distributor deduction matching","Execute distributor deduction matching using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed distributor deduction matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Distributor deduction matching Reference","text","BDA11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("claim-approval-workflow","BDA12","Claim approval workflow","Execute claim approval workflow using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed claim approval workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Claim approval workflow Reference","text","BDA12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("credit-memo-reconciliation","BDA13","Credit memo reconciliation","Execute credit memo reconciliation using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed credit memo reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Credit memo reconciliation Reference","text","BDA13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("accrual-true-up","BDA14","Accrual true-up","Execute accrual true-up using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed accrual true-up decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Accrual true-up Reference","text","BDA14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]}),
feature("brand-distributor-analytics","BDA15","Brand distributor analytics","Execute brand distributor analytics using distribution agreements, products, territories, depletion reports, accounts, volume tiers, price promotions, billbacks, allowances, claims, and credits.","Produce a governed brand distributor analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Brand Program","text","Distributor / Brand Program · Standard Case"],["caseReference","Brand distributor analytics Reference","text","BDA15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1401250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1695513],["domainDriver","Allowance Type","select","Depletion",["Depletion","Billback","Display allowance"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Distributor agreement library case","Brand SKU registry case","Territory account mapping case","Depletion report ingestion case","Account eligibility validation case"]})
]);
